name: Deploy Portfolio

on:
  push:
    branches:
      - main  # sempre que der push no main, vai tentar deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Pega o código do repositório
      - uses: actions/checkout@v3

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instala dependências
      - run: npm ci

      # Build do Vite
      - run: npm run build

      # Publica no GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist